//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimaSzamlaAdatbazissal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualDBTable
    {
        public int Id { get; set; }
        public string cpName { get; set; }
        public int cpDB { get; set; }
        public int cpFulValue { get; set; }
        public string cpDate { get; set; }
    }
}
