//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimaSzamlaAdatbazissal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommercialPaperSells
    {
        public int Id { get; set; }
        public string cpName { get; set; }
        public string cpDate { get; set; }
        public string cpTime { get; set; }
        public int cpValue { get; set; }
        public int cpAmount { get; set; }
        public int cpSumcom { get; set; }
        public int cpWinning { get; set; }
    }
}
