//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimaSzamlaAdatbazissal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommercialPaperFix
    {
        public int Id { get; set; }
        public string cp_name { get; set; }
        public string cp_date { get; set; }
        public string cp_time { get; set; }
        public int cp_value { get; set; }
        public int cp_amount { get; set; }
        public int sumcom { get; set; }
    }
}
